using Safeware.Saba.Ng.Shared;
using Book;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Safeware.Saba.Ng.Permissions;
using Safeware.Saba.Ng.ChildEntities;

namespace Safeware.Saba.Ng.ChildEntities
{
    public class ChildEntitiesAppService : ChildEntitiesAppServiceBase, IChildEntitiesAppService
    {
        //<suite-custom-code-autogenerated>
        public ChildEntitiesAppService(IChildEntityRepository childEntityRepository, ChildEntityManager childEntityManager, IRepository<Book.Book, Guid> bookRepository)
            : base(childEntityRepository, childEntityManager, bookRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}