version: '3.7'

services:
  ng-web:
    image: safeware.saba/ng-web:latest
    container_name: ng-web
    build:
      context: ../../../
      dockerfile: angular/Dockerfile.local      
    ports:
      - "4200:80"
    depends_on:
      - ng-api
    volumes:
      - ./dynamic-env.json://usr/share/nginx/html/dynamic-env.json
    networks:
      - abp-network  

  ng-api:
    image: safeware.saba/ng-api:latest
    container_name: ng-api-container
    build:
      context: ../../
      dockerfile: Safeware.Saba.Ng/Dockerfile.local
    environment:
      - ASPNETCORE_URLS=https://+:443;http://+:80;
      - Kestrel__Certificates__Default__Path=/root/certificate/localhost.pfx
      - Kestrel__Certificates__Default__Password=91f91912-5ab0-49df-8166-23377efaf3cc
      - App__SelfUrl=https://localhost:44348
      - AuthServer__Authority=http://ng-api
      - AuthServer__RequireHttpsMetadata=false
      - AuthServer__SetSelfAsIssuer=true      
      - Redis__Configuration=redis
    ports:
      - "44348:443"
    depends_on:
      redis:
        condition: service_healthy  
    restart: on-failure    
    volumes:
      - ./certs:/root/certificate
    networks:
      - abp-network  
  
  db-migrator:
    image: safeware.saba/ng-api:latest
    container_name: db-migrator
    build:
      context: ../../
      dockerfile: Ng/Dockerfile.local
    environment:
    command:
      - --migrate-database
    depends_on:
    networks:
      - abp-network    

  redis:
    container_name: redis
    image: redis:7.2.2-alpine
    ports:
      - "6379:6379"
    networks:
      - abp-network  
    healthcheck:
      test: ["CMD", "redis-cli","ping"]      

volumes:

networks:
  abp-network:
    name: ng-network
    driver: bridge