using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Safeware.Saba.Ng.ChildEntities
{
    public class ChildEntityManager : ChildEntityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ChildEntityManager(IChildEntityRepository childEntityRepository)
            : base(childEntityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}