using Book;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Safeware.Saba.Ng.ChildEntities
{
    public class ChildEntity : ChildEntityBase
    {
        //<suite-custom-code-autogenerated>
        protected ChildEntity()
        {

        }

        public ChildEntity(Guid id, Guid masterEntityId, Guid? bookId, bool enabled, string? name = null)
            : base(id, masterEntityId, bookId, enabled, name)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}