using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Safeware.Saba.Ng.MasterEntities
{
    public class MasterEntity : MasterEntityBase
    {
        //<suite-custom-code-autogenerated>
        protected MasterEntity()
        {

        }

        public MasterEntity(Guid id, int cost, string address, string? name = null)
            : base(id, cost, address, name)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}