using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Safeware.Saba.Ng.MasterEntities
{
    public class MasterEntityManager : MasterEntityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public MasterEntityManager(IMasterEntityRepository masterEntityRepository)
            : base(masterEntityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}